### PR TITLE
Create enemies

### LINKED ISSUE #17: Create enemies

### PR DESCRIPTION
**Pull request by marcosvnmelo**

### CODE REVIEW

**Comment by marcosvnmelo** [comment]
Create crusher

**Comment by marcosvnmelo** [comment]
Create bee blader

**Comment by marcosvnmelo** [comment]
Create gun volt

**Comment by marcosvnmelo** [comment]
Create road attacker

**Comment by marcosvnmelo** [comment]
Create bomb been

**Comment by marcosvnmelo** [comment]
Create jamminger

**Comment by marcosvnmelo** [comment]
Create ball de vaux

**Comment by marcosvnmelo** [comment]
Create spiky

**Review by Manuel-Antunes — APPROVED** [review]
Nice!

**Pull request merged**
